### ISSUE TITLE
Sphere kernel with Jax gives an error

### ISSUE THREAD

**Issue by NoemieJaquier** [GPflow/GeometricKernels#41]
```
import numpy as np
import jax.numpy as jnp

import geometric_kernels.jax

from geometric_kernels.spaces.hypersphere import Hypersphere
from geometric_kernels.kernels.geometric_kernels import MaternKarhunenLoeveKernel

_TRUNCATION_LEVEL = 10
_NU = 2.5
_LENGTHSCALE = 1.0

if __name__ == '__main__':
    # Parameters
    dimension = 3
    nb_samples = 10

    # Create manifold
    hypersphere = Hypersphere(dim=dimension)

    # Generate samples
    xs = hypersphere.random_point(nb_samples)

    # Kernel
    kernel = MaternKarhunenLoeveKernel(hypersphere, _TRUNCATION_LEVEL)
    params, state = kernel.init_params_and_state()

    # Jax backend
    params["nu"] = jnp.r_[_NU]
    params["lengthscale"] = jnp.r_[_LENGTHSCALE]
    print(kernel.K(params, state, jnp.array(xs)))
```

The above code gives the following error:

```
Traceback (most recent call last):
  File "/home/noemie/Documents/KIT/BoManifolds/GeometricKernels/tests/kernels/matern_sphere_backends.py", line 50, in <module>
    print(kernel.K(params, state, jnp.array(xs)))
  File "/home/noemie/Documents/KIT/BoManifolds/GeometricKernels/geometric_kernels/kernels/geometric_kernels.py", line 128, in K
    return Phi.weighted_outerproduct(weights, X, X2, **params)  # [N, N2]
  File "/home/noemie/Documents/KIT/BoManifolds/GeometricKernels/geometric_kernels/eigenfunctions.py", line 130, in weighted_outerproduct
    sum_phi_phi_for_level = self._addition_theorem(X, X2, **parameters)  # [N, N, L]
  File "/home/noemie/Documents/KIT/BoManifolds/GeometricKernels/geometric_kernels/spaces/hypersphere.py", line 93, in _addition_theorem
    for level in self._spherical_harmonics.harmonic_levels
  File "/home/noemie/Documents/KIT/BoManifolds/GeometricKernels/geometric_kernels/spaces/hypersphere.py", line 93, in <listcomp>
    for level in self._spherical_harmonics.harmonic_levels
  File "/home/noemie/Documents/PythonLibraries/venvs_python/venv_GeometricKernels/lib/python3.7/site-packages/spherical_harmonics/spherical_harmonics.py", line 176, in addition
    c = self.gegenbauer(XYT)  # [N1, N2]
  File "/home/noemie/Documents/PythonLibraries/venvs_python/venv_GeometricKernels/lib/python3.7/site-packages/spherical_harmonics/gegenbauer_polynomial.py", line 157, in __call__
    return polyval(self.coefficients, x)
  File "plum/function.py", line 537, in plum.function.Function.__call__
  File "/home/noemie/Documents/PythonLibraries/venvs_python/venv_GeometricKernels/lib/python3.7/site-packages/spherical_harmonics/lab_extras/jax/extras.py", line 22, in polyval
    return jnp.polyval(coeffs, x)
  File "/home/noemie/Documents/PythonLibraries/venvs_python/venv_GeometricKernels/lib/python3.7/site-packages/jax/_src/numpy/polynomial.py", line 224, in polyval
    _check_arraylike("polyval", p, x)
  File "/home/noemie/Documents/PythonLibraries/venvs_python/venv_GeometricKernels/lib/python3.7/site-packages/jax/_src/numpy/util.py", line 295, in _check_arraylike
    raise TypeError(msg.format(fun_name, type(arg), pos))
TypeError: polyval requires ndarray or scalar arguments, got <class 'list'> at position 0.

Process finished with exit code 1
```

**Comment by vabor112** [comment]
Ran into the same issue while designing doctests.

**Comment by stoprightthere** [comment]
This issue should be fixed with this [PR](https://github.com/vdutor/SphericalHarmonics/pull/8)  to [SphericalHarmonics](https://github.com/vdutor/SphericalHarmonics).

**Comment by NoemieJaquier** [comment]
I confirm that it is fixed, thanks!
