### ISSUE TITLE
License Restrictions

### ISSUE THREAD

**Issue by BinglinW** [GPflow/GeometricKernels#96]
hi, When I run gpr_torch and gpr_jax, I run into the following license restrictions. This license needs to be purchased. But now I need to learn how to use the toolkit by these examples. Could you provide a simpler example, for example through a test function?
```
Error: Unable to find valid license for MeshPro. 

Add a license with


    plm add <your-license-key>

You're creating a mesh with more than 100 for which a MeshPro license is required. See https://github.com/meshpro for details.

An exception has occurred, use %tb to see the full traceback.

Traceback (most recent call last):

  File "<string>", line 20, in _7SO8Y

  File "<string>", line 4, in wrapper

  File "<string>", line 314, in _WnDje

  File "<string>", line 4, in wrapper

  File "<string>", line 354, in _rkcVS

_ZIsyv: Unable to find valid license for MeshPro. 

Add a license with

    plm add <your-license-key>



During handling of the above exception, another exception occurred:

SystemExit: 1
```

**Comment by BinglinW** [comment]
> Hey @BinglinW, thank you for pointing that out!
> 
> Seems like `meshzoo` library that we used to create a mesh for the example, now requires a license. Luckily, you don't need `meshzoo` to use our library.
> 
> For example, you can use the mesh in `notebooks/data/teddy.obj`. You can load it via:
> 
> ```python
> from geometric_kernels.spaces.mesh import Mesh
> mesh = Mesh.load_mesh(<path/to/teddy.obj>)
> ```
> 
> Internally, it uses [potpourri3d](https://github.com/nmwsharp/potpourri3d) library to read the file and create two arrays: `V` with vertices and `F` with face indices. Of course, you can load any other mesh, provided you have a file. Please refer to the potpourri3d documentation for the details on which files are supported.
> 
> Hope this helps! We will update our examples to avoid this issue in the future.
> 
> Thanks for the interest in our library!

Hi, the solution works well. thanks for your help
